name: pyiron_example_env
channels:
- conda-forge
dependencies:
- jupyterlab
#- python
- pyiron
- pyiron_base
- lammps
- iprpy-data
- sphinxdft >=2.7.0
- sphinxdft-data
- nglview
- seaborn
- pyscal
- pyiron-data >=0.0.5
- sqsgenerator
- pymatgen
- jupyterlab-link-share
# LSP
- jupyterlab-lsp
- autopep8
- flake8>=3.8.0
- pycodestyle>=2.6.0,<2.7.0
- pydocstyle>=2.0.0
- pyflakes>=2.2.0,<2.3.0
- pylint>=2.5.0
- yapf
- rope>=0.10.5
# other extensions
#- jupyterlab-git
#- jupyterlab-spellchecker
#- jupyterlab-spreadsheet-editor
#- gower==0.0.5
#- scikit-learn
#- plotnine
#- umap-learn
